language: python
python:
- '3.5'
- '3.6'
matrix:
  include:
    # Direct Python support is not yet supported in Travis so manual installation
    # via choco and conda is required for now. Based on tips grafted from
    # https://travis-ci.community/t/python-support-on-windows/241/4
    - os: windows
      language: sh
      python: '3.7'
      filter_secrets: false
      before_install:
        - choco install miniconda3
        # python is in miniconda3, conda is in miniconda3/Scripts, openssl is in miniconda3/Library/bin
        - export PATH="/c/Tools/miniconda3:/c/Tools/miniconda3/Scripts:/c/Tools/miniconda3/Library/bin:$PATH"
        - conda install shapely numpy --yes

git:
  lfs_skip_smudge: true
before_install:
- pip install --upgrade pip==19.3.1 setuptools==45.1.0 wheel==0.33.6
install:
- pip wheel --no-deps --wheel-dir wheels -e .
- pip install `ls wheels/*.whl`\[complete,tests\]
# hack, until this pip bug is fixed: https://github.com/pypa/pip/issues/988
# see: https://github.com/HypothesisWorks/hypothesis/issues/2113
- pip install --upgrade hypothesis
script:
- pytest -rfExXP --assert=plain --ignore-glob="*/smoke_tests" --ignore="descarteslabs/third_party/" --pyargs descarteslabs
