name: Slack
on: [check_suite]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      # if: ${{ github.event.action }} == "completed"
      run: |
        curl -H "Content-Type: application/json" -X POST -d '{ "text": "CI testing of ${{ github.event.repository.full_name }} has ${{ github.event.check_suite.conclusion }} for commit ${{ github.event.check_suite.after }} ${{ github.event.check_suite.url}}" }' ${{ secrets.slack_webhook }}

